eks_task:
  eks_container:
    image: ${CIRRUS_AWS_ACCOUNT}.dkr.ecr.eu-central-1.amazonaws.com/base:j11-latest
    region: eu-central-1
    cluster_name: ${CIRRUS_CLUSTER_NAME}
    cpu: 1
    memory: 1G
  script: mvn --version
